import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';

// Component Imports
import Header from '@/components/layout/Header';

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Portofolio - Lakha',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${openSans.variable} antialiased bg-gradient-to-br from-purple-900 to-slate-800 w-11/12 md:4/5 mx-auto`}>
        <Header />
        <main className='h-full'>
          {children}
        </main>
      </body>
		</html>
	);
}
