import type { Metadata } from 'next';
import { Caveat, Open_Sans } from 'next/font/google';
import './globals.css';

// Component Imports
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});

const caveat = Caveat({ 
	subsets: ['latin'], 
	weight: ['400', '700'], 
	variable: '--font-caveat' 
});

export const metadata: Metadata = {
	title: 'Portofolio - Lakha',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${openSans.variable} ${caveat.variable} antialiased bg-gradient-to-br from-purple-900 to-slate-800 w-11/12 md:4/5 mx-auto`}>
				<Header />
				<main className="h-full">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
